### PR TITLE
Initial docstring updates.

### PR DESCRIPTION
**Pull request by Sasafrass**
This is a Work In Progress PR in which we should attempt to update all missing docstrings. To see which docstrings still have to be written, cmd into the "app" folder and do ```pydocstyle``` (if pydocstyle is installed). Please feel free to add and commit as many docstrings to functions to this PR as you like. Re-running pydocstyle will tell you whether the written docstring fulfills the criteria. 

I have made a quick start with implementing a number of docstrings that were missing in the models module.

### CODE REVIEW

**Comment by annaproxy** [comment]
I removed the old helpers.py and slangreader.py. This is done in different files. There were no further references to it (and we can dig them up from git history if necessary)

**Comment by Sasafrass** [comment]
Cool. Indeed, they had redundant functionality so it is fine to remove them.

**Comment by Sasafrass** [comment]
Removed Work In Progress label. Should now pass Pydocstyle for the entire project, including the /app folder and the parent folder files (config.py and straattaal.py) - please double check.

**Review by annaproxy — APPROVED** [review]
looks good & still runs

**Pull request merged**
