### PR TITLE
Create MIT License

### PR DESCRIPTION
**Pull request by Sasafrass**
Add the MIT License to the repository.

### CODE REVIEW

**Comment by annaproxy** [comment]
I like copyleft licenses more for non-academic work, but MIT is fine, too, if you prefer it

**Comment by raoulg** [comment]
Why not pick a Creative Commons?

**Comment by Sasafrass** [comment]
Hmm, copyleft is still up for debate imo, but Creative Commons appears to be a bit restrictive in terms of the (non-)commercial use. I think this link https://www.whitesourcesoftware.com/resources/blog/open-source-licenses-trends-and-predictions/ provides some good arguments in terms of the trends in preference among other companies

**Comment by annaproxy** [comment]
GPL :D

**Pull request closed without merging**
